name: Create release
description: Create release GitHub action
author: Lapiniot

inputs:
  name:
    description: The name of the release
    required: true
  tag_name:
    description: The name of the tag
    required: true
  body:
    description: Text describing the contents of the tag
    required: true
  prerelease:
    description: true to identify the release as a prerelease. false to identify the release as a full release
    required: false
  draft:
    description: true to create a draft (unpublished) release, false to create a published one
    required: false
  generate_release_notes:
    description: Whether to automatically generate the name and body for this release.
    required: false
  make_latest:
    description: Specifies whether this release should be set as the latest release for the repository
    required: false

outputs:
  id:
    description: The unique identifier of the release
  html_url:
    description: User accessible URL for the release created
  upload_url:
    description: Assets upload target URL

runs: 
  using: node20
  main: dist/index.js